In [1]:
import numpy as np
import pandas as pd

In [4]:
country = ["india ", "uk" ,"us" ,"china" , "japan" , "france" ]
pd.Series(country)

0    india
1        uk
2        us
3     china
4     japan
5    france
dtype: object

In [10]:
subject = ["english","hindi","maths", "cse"]
marks = [90,91,92,93]
marks_series =pd.Series(marks,index=subject,name="vijay'smarks")
print(marks_series)

english    90
hindi      91
maths      92
cse        93
Name: vijay'smarks, dtype: int64

In [17]:
vk = pd.read_csv("kohli_ipl.csv",index_col='match_no')
print(vk)

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [20]:
vk.head(3)

          runs
match_no
1            1
2           23
3           13

In [21]:
vk.tail(4)

          runs
match_no
212         20
213         73
214         25
215          7

In [24]:
vk.sample(4)

          runs
match_no
78          32
23          19
89          21
8            0